sudo: required

dist: trusty

services:
  - docker

jdk:
- oraclejdk8

before_install:
- echo $GPG_PASSWORD | gpg --passphrase-fd 0 releng/enilink.asc.gpg
- gpg --import releng/enilink.asc

script: if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ] || [ "$TRAVIS_BRANCH" = "snapshots" ]; then mvn deploy -B -P ossrh,release -s ./.travis.maven-settings.xml; else mvn verify -B; fi

deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: r37g9AAVTPckSKJbvCVcUxgkfV3PuhE0952KdI3U+mBtWXWiL3zN8wYDZc1LFIzvk/DuVKKG6s4KBxpRzfgTyS75h7WJ9NjIyUWYduFns6loo8vUVh84QWf41R8sin9MxObRMyBkbqsu4AVYmU4+Tnk0iFrjA0dBwTiMkDLz8/Bz+JgjxMHXKCcciILRzBCajrYt035wvPU1HFhG5aEno8HehwJ0YHV9aF5TqwpbcoL3iJKrIDyy2ydxnQSrTzZo5CrOqiJrZhFvZn5VciErohBLBTnEiMB/mzNmS2INmGglCWuzgd/9niKi/9nPKwkBFmVSWQBGlnqSVCg5GUcmpEDixX6bMjYbZ4lCeb+ZTF9MuZ4Js5w/mlAw8cUVUD3OWWnNbOVAZCWud0XbPRiD1vgV9XqfaDvWq9F7wdhgNHh0jzR9MFxQ/dFKhkYUIjKkmQE5UyuX6aASYhWW26ZgOIeMjSEl9X/JNXQ1MID57TTyglklRzOa3U8psETqUkc2cnB5yK7U29PXwJAP8B2o06+8UzJNeK6x+weHdbPUTcn3bLyfMsUcDPcyh2YcZ7Ree6AD3UuFFNydRDuYci/PGFpYc6lQD1y9pHJKSJ2UVB0P8JSMF6nmDxqIh4rZg6xx3OrLyY1C5LVg7yV/sRJB+5VbPnXLtPl7kWj2VPCdJ+A=
  file_glob: true
  file: products/enilink-server/target/enilink-server-*{.zip,.tar.gz}
  on:
    repo: enilink/enilink
    tags: true
#- provider: script
#  skip_cleanup: true
#  script: releng/publish/pushToDockerHub.sh
#  on:
#    branch: snapshots
#- provider: script
#  skip_cleanup: true
#  script: releng/publish/pushToDockerHub.sh
#  on:
#    tags: true

env:
  global:
  - BINTRAY_USER: kenwenzel
  - BINTRAY_OWNER: enilink
  - BINTRAY_REPO: updates
  - BINTRAY_PCK_NAME: enilink
# BINTRAY_API_KEY
  - secure: "I2G+UaDhVtAGGL2O043ZqljcKRG832XyrvCbHZRf/j4TJWQli/BA7kZ+FTW9nG6AaTfGLwqDDYEov+tRTopb09ler4byrb+wqkM/ngvXOrTCrXJU3I969LrL1S4CVgcBnHUVW5hJGir8bYcxMpPtAVVIKF4t3h27cFL9t4J7rVptS4r6Da8+BnxKnuURNCn14x02qhuoZlqwznP6XB0IGIFoqXmCm3yBNtwHn02e8WJV+4Bo4tMTYmJF6pkZfcZKHnMBdo5LqEyhPFK+eDjqLiUXB+50RxQ2w3xmtpUEF6t7rfCTvUf+9CMba7PKiIbPUTb+dNTEvrNxCtCwGLKw1N9Kc0OANEsa38xciT8vZUzuAllghnK+QsjT1TcJe7WP3l6SO/kvurEg5kFb/D2I/0v/KSh5ItNb43YcY/VjX3tnl81CElyKinzegcPJo1jfsjNo84BHKeXIlXtmjiwaYbm+uMBveAHyiuYbXlH65Kne8W2mQNt4vHS+Pfl4/uJrt8einN4SPl79t0DW8UmDNCxqIiSvRQOzo1HRvlVdeIT39nYDEH/puE8THNKxnn2VPSIEh2eJzBYHMsLxIyHkf776fF1CyncEYRU/7idNSVCgVzM1L7JCg7GL0mnb+tao4+nqG5f/5p1kfdJhyYmckiwinnJ6DvM78nL6j6+/+Dw="
  - DOCKER_USER: kenwenzel
# DOCKER_PASS
  - secure: "XmfHD46JSHGp1fAFRvT9mKovLD5YYmkDJSdPb/DEO5Zp0C0JAyKFbS7KY36yB/pHK1GFSrDZ2nBUhys+g+O08ohsmOC2CmCHorVIyt+IAxFj+6HD+MljbU88d7vWmkuWIL2lUscrc9P+WuJOPL1GEiG0MB7QbMJr9vMwnN9uepaq76Gpqc4K86Io61t/AtqGvkyWQoSrY6LYgCmHVnYQpUUGe+BPbNn+I5QhVZ105YrQDywLsVy22bJ1M5BNymrTlEWh6Jc31Y6CyGXFSwQUFTbbM+aM9+yV4UxKJ0MVp/Lcxrz4+uiy/tXdFNO5GVCwYX/c8/hc1WhZsPKWxGjwbfsnLT6wSztG+5MV31U4r3rWqiSF57fsV/lQJ9X4GyRrb+d1249dRTCsECdKY26r99RB1eF7uHHHWmW34jnaifEAArDfEHLOAWYyoh2bD2aa4uzKU4HyZp8SgZSVEtDDtSuCOlLJaHmCcZOw5NJbnQ+LsuC6C9QAe4CN0cl4RwzajWtWIiO/6SHhtu8A13uYJ3Q0G8hC3/obi9304Ffs32FCiL/OMTRDrQXa6QqjZ91cdFK0r6Z1Vz9zp3BaaiV6UjpRid3ZDpK0TUqUy9XG3Ai8fzmsxS3IeTW0/84ZarWkOQkIsVHAKLGNJbL1iL5Kft2j0LmsuZB0a+CzYDbLw40="
# GPG_PASSWORD
  - secure: "kUlEtuo8lgqglzLF9KoX9acw7z+sAWH2KWjico42EoHFnzMjAWtB++QaLO5PHH5tvLUSGK8GtJwagw6k4+LPO/R8rbOzsfmFzLlBA2fspuD7Z3ldydEQeRYv0V7RdtCLGFcb+wAGh6vkk5gZviefIaah1K+h7FF2P3lPZ6+nA/SYAUQt5vRw85DPFwxxM4jnAG3te5+UcIjFhI8hmUMHUEn9qShB6JUtiU7TSVvKMN6UFvT20C76ulhwjw80h14Ypnm12dgcJIJ8kS3m62FvqpZGzmPx7O/9uW1GRDtDnNhFNoI8caZWvqKmbYaXQEyhn8Z0sAhAlgQeGJTloAVHPMtr85jrrrpRTXIHf2hvdidyZ8AURJKAlofFFtM656zh9WirTGz2+ktd30V/OE8XTSo8lTaD9nTtCuAU01iHp+2hNsoJyCoHug7sYaUUm1ZcuELVScAOWeP5Z6IJv7GcvJvojyQU+m0WVwqnXj8iISOopBKN3TFNUsu0OFxoPprDLpL8y61fxTenKtizOS3/wfF5hUW3RvGsfmJnae0Ej8ibZC5l1FL1CScGsOKPcSsZ5ZsLkiaUttsHmCVX/l/b1pZyDgXJB5xpL8Djo2N7uyao2Zfa6lr/IWwzsPvoqD1DGi/OGe4H5PDjuyGFgpoE8T+GfNz82siC8HoaPQB1wks="
# SONATYPE_USER
  - secure: "g/eiTZZ1+LIiw+6MDaVUHQ5g+fDASJIVwDHFn+g8cU4klduGa1GV1Lo17kM8jnlb6GZINwBPgT4iYVqQIDv59R2fACmj2zk0a7C9B+zAWzEDaBfvbcy4b5OSvcdt8cqHc59g31y5WxTTGOaQjDE31+aon5yYNetGQ7uo8vbl0CmAyfbT1n4cR8apok2/k9x8mZRXvNn0geHC/eNcqDKQPyB04+FmKLRjlV2LuO8QkPwGHtdTwCynCfKddZcar8MAggTXmd/Kkpo7CQ3fAcBLVqfi4wYO4tBoD44tNmh470eoQ3aMoFtJ9c4ys02JIh1SD2axVIZDHqI15jOD7kfgrOIEUzmN38twAm1b8j20pgYTQ0oa3HeIEth/0nlEIsVtyPSgGMpDGLISv7eA4dBrkjLYMttvPeDpcYiBcRxezGQkxy18iv7zn+hyKBhQQ2kiIDN/4CnDgzIgL7oFyu6Ua4I19R14f36Y0Mx/SRAh4Kc0hjLAK/C3u0EAF2E7Kw9PAZV+DNHFmphI4cEv48p8VhAII2PlCH2KB98HJM8dAZ+INyrnHNF711wxn4bfLPCImfXeB9nntmztDDDcHGMjhNo9O0HByNipjqqtJdoI7uqMt0C7Ry72q34MkB7qJifwYENsDu7f0WtgcTgP+L3Nuj01cnC2L5Iuvnn6EuGIShg="
# SONATYPE_PASSWORD
  - secure: "ZdFhMGW4Ae9AHsJDCT2ml6o6xwDYlKaqMcmSGI5V9+zu3S6BjCgorGXhgxdw5fapmoaJbkAWG/Wx5/Czo3HPlX/PvTGIThp3frxeL8dRxTxxwql45i+aBpt6FLSGLmmMsf3As+Exd1KIARjBYqF5iJVae/SMgDSidVfnyF2amS00S3Av/dpzxOwsi9GEYq5oHrAgbHwB+j+R7Cl/RkCJzYKbtOdKa61XLdIJ1UQqsLwbU30xDtH8uSb9WwVx1j0PUVsGKRt0RWaiGSUwdMQuXicL+8kL36E03bzWOqUM5X0CTNoQ6zbUhvFVWvev3CJMZ87vGqCM/wObPDZChsuQZksWftG0NEdvtgEMddrc2IhlV9yMBDrTC3w+KXkdSJP8tNAxoiFaFliafzXG43TGgnmsgjH+iUnU1AqWjhOCUe8IeF319QNN9Bxjd+ho9IJygwbsVuJ30VA0syhu4qOu3V5uGSIPw3UTxOfoH523OxZ/ylq7F07FiBlW9FXPGRNWdXEwjRkS7AXmG5Q8ZCO3doSpgaJ61U1FdtRfRzfJmeNKF4xd+L7APEQSkdsuhKgNUjBPwn/rrisYoeX29r8k92Or0UJpqFa2F1onrIwHphIWo3ZpJ4WTTZyUmxjW/I89IdwchzYDAQrhaBzGoATYNFVKR12von7kqmfWv11NpqE="
